version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "YOUR_IP_ADDRESS:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://YOUR_IP_ADDRESS:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"